miraniumCoef=6
revenueCoef=1
threshold.ARC_SAND_ORE=1
threshold.AURORITE=1
threshold.BOILED_EGG_ORE=1
threshold.BONJELIUM=1
threshold.CIMMERIAN_CINNABAR=1
threshold.DAWNSTONE=1
threshold.ENDURON_LEAD=1
threshold.EVERFREEZE_ORE=1
threshold.FOUCAULTIUM=1
threshold.INFERNIUM=1
threshold.LIONBONE_BORT=1
threshold.MARINE_RUTILE=1
threshold.OUROBOROS_CRYSTAL=1
threshold.PARHELION_PLATINUM=1
threshold.WHITE_COMETITE=1
iterations=10000
initialPopulationSize=100
selectionByElitismCount=3
selectionByTournamentCount=17
tournamentSize=3
crossoverOnSelectionCount=15
crossoverOnRandomCount=15
mutationCount=25
mutationSwapRate=0.05
mutationReplaceRate=0.05
randomInjectionCount=25