iterations=10000
initialPopulationSize=100
selectionByElitismCount=3
selectionByTournamentCount=17
tournamentSize=3
crossoverOnSelectionCount=15
crossoverOnRandomCount=15
mutationCount=30
mutationSwapRate=0.05
mutationReplaceRate=0.05
randomInjectionCount=20